EE5121 - Convex Optimization  
Assignment 1 - Question 1

In [12]:
#imports
import cvxpy as cp
import numpy as np

In [13]:
#Constant matrix A, vector b and 1-vector
A = np.array([[1,0,1],[0,1,1],[1,1,2]])
b = np.array([0.2,0.8,1])
one = np.array([1,1,1])

In [14]:
#Decision Variables
x = cp.Variable(3)
u = cp.Variable(3)

(d)

In [15]:
#Formulating the problem
objective = cp.Minimize(one.T@u)
constraints = [A@x == b, -u <= x, x <= u, u >= 0]
prob = cp.Problem(objective=objective,constraints=constraints)

In [16]:
#minimum and the optimizer
print("Optimal objective value", prob.solve())
print("Optimal variable value")
print(x.value)

Optimal objective value 0.799999999127884
Optimal variable value
[2.67594184e-09 6.00000003e-01 1.99999997e-01]


In [17]:
print(u.value)

[1.81280449e-09 6.00000001e-01 1.99999996e-01]


(e)

In [18]:
#different device
b = np.array([0.2,0.8,0.95])

In [19]:
#reformulating problem 
objective = cp.Minimize(one.T@u + 1*cp.norm(A@x - b))
constraints = [-u <= x, x <= u, u >= 0]
prob = cp.Problem(objective=objective,constraints=constraints)

In [20]:
#minimum and the optimizer
print("Optimal objective value", prob.solve())
print("Optimal variable value")
print(x.value)

Optimal objective value 0.799999999858534
Optimal variable value
[6.62878513e-12 5.50000921e-01 1.99999654e-01]


In [21]:
print(u.value)

[3.84883164e-10 5.50000921e-01 1.99999654e-01]


In [22]:
#residual 
print(np.linalg.norm(A@x.value - b))

0.04999942515303242
